# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: ruby

rvm:
  - 2.6.3
  - 2.5.5
  - 2.0.0

# job phases

before_install:
  - gem build macaddress.spec

install:
  - gem install macaddress

script:
  - rake test
