# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: ruby

rvm:
  - 2.6.3
  - 2.5.5

# job phases

before_install:
  - bundle update --bundler

install:
  - bundle install --with=development

script:
  - bundle exec rake test
